services:
  rag-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: showcase-rag-app
    environment:
      CHUNKING_STRATEGY: "simple"
      CHUNK_SIZE: 512
      CHUNK_OVERLAP: 64
      METADATA_FILTER: "False"
      METADATA_ENHANCEMENT: "False"
      POST_BM25_RERANK: "False"
      OLLAMA_MODEL: "llama3:8b"
      RAG_QUESTION_LIMIT: 8
      MAX_TOKENS: 512
    depends_on:
      - ollama

  ollama:
    container_name: showcase-ollama
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama
    environment:
      OLLAMA_MODEL: llama3:8b
