services:
  rag-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: showcase-rag-app
    depends_on:
      - ollama

  ollama:
    container_name: showcase-ollama
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama
    environment:
      OLLAMA_MODEL: llama3:8b
