services:
  rag-app:
    image: ${RAG_APP_IMAGE:-enviteconsulting/showcase-rag-greenmetrics:demo}
    container_name: rag-app
    depends_on:
      - ollama
    docker-run-args:
      - --gpus=all

  ollama:
    container_name: ollama
    image: ollama/ollama@sha256:d4188c1dfa870386a14e299976aed96daeb83876b69e1a852c9d09ea76463b9f
    docker-run-args:
      - -v ollama:/root/.ollama:ro
      - --gpus=all
